name = "Meteor More Mine"
description = "Meteor will bring marble and gems."
author = "[BSy]Jupiter"
version = "1.0.4"
forumthread = ""

api_version = 10

icon_atlas = "modicon.xml"
icon = "modicon.tex"

all_clients_require_mod = false
client_only_mod = false
dst_compatible = true
server_filter_tags = {"Meteor More Mine"}

configuration_options =
{
	{
		name = "rocks",
		label = "Extra Rocks Drop",
		hover = "the probability of dropping rocks in addition.",
		options =	{
						{description = "0", data = 0, hover = ""},
						{description = "0.25%", data = 0.0025, hover = ""},
						{description = "0.5%", data = 0.005, hover = ""},
						{description = "0.75%", data = 0.0075, hover = ""},
						{description = "1%", data = 0.01, hover = ""},
						{description = "2%", data = 0.02, hover = ""},
						{description = "3%", data = 0.03, hover = ""},
						{description = "4%", data = 0.04, hover = ""},
						{description = "5%", data = 0.05, hover = ""},
						{description = "6%", data = 0.01, hover = ""},
						{description = "7%", data = 0.01, hover = ""},
						{description = "8%", data = 0.01, hover = ""},
						{description = "9%", data = 0.01, hover = ""},
						{description = "10%", data = 0.1, hover = ""},
						{description = "20%", data = 0.2, hover = ""},
						{description = "30%", data = 0.3, hover = ""},
						{description = "40%", data = 0.4, hover = ""},
						{description = "50%", data = 0.5, hover = ""},
					},
		default = 0.1,
	},
	{
		name = "flint",
		label = "Extra Flint Drop",
		hover = "the probability of dropping flint in addition.",
		options =	{
						{description = "0", data = 0, hover = ""},
						{description = "0.25%", data = 0.0025, hover = ""},
						{description = "0.5%", data = 0.005, hover = ""},
						{description = "0.75%", data = 0.0075, hover = ""},
						{description = "1%", data = 0.01, hover = ""},
						{description = "2%", data = 0.02, hover = ""},
						{description = "3%", data = 0.03, hover = ""},
						{description = "4%", data = 0.04, hover = ""},
						{description = "5%", data = 0.05, hover = ""},
						{description = "6%", data = 0.01, hover = ""},
						{description = "7%", data = 0.01, hover = ""},
						{description = "8%", data = 0.01, hover = ""},
						{description = "9%", data = 0.01, hover = ""},
						{description = "10%", data = 0.1, hover = ""},
						{description = "20%", data = 0.2, hover = ""},
						{description = "30%", data = 0.3, hover = ""},
						{description = "40%", data = 0.4, hover = ""},
						{description = "50%", data = 0.5, hover = ""},
					},
		default = 0.1,
	},
	{
		name = "goldnugget",
		label = "Extra Gold Nugget Drop",
		hover = "the probability of dropping gold nugget in addition.",
		options =	{
						{description = "0", data = 0, hover = ""},
						{description = "0.25%", data = 0.0025, hover = ""},
						{description = "0.5%", data = 0.005, hover = ""},
						{description = "0.75%", data = 0.0075, hover = ""},
						{description = "1%", data = 0.01, hover = ""},
						{description = "2%", data = 0.02, hover = ""},
						{description = "3%", data = 0.03, hover = ""},
						{description = "4%", data = 0.04, hover = ""},
						{description = "5%", data = 0.05, hover = ""},
						{description = "6%", data = 0.01, hover = ""},
						{description = "7%", data = 0.01, hover = ""},
						{description = "8%", data = 0.01, hover = ""},
						{description = "9%", data = 0.01, hover = ""},
						{description = "10%", data = 0.1, hover = ""},
						{description = "20%", data = 0.2, hover = ""},
						{description = "30%", data = 0.3, hover = ""},
						{description = "40%", data = 0.4, hover = ""},
						{description = "50%", data = 0.5, hover = ""},
					},
		default = 0.1,
	},
	{
		name = "nitre",
		label = "Extra Nitre Drop",
		hover = "the probability of dropping nitre in addition.",
		options =	{
						{description = "0", data = 0, hover = ""},
						{description = "0.25%", data = 0.0025, hover = ""},
						{description = "0.5%", data = 0.005, hover = ""},
						{description = "0.75%", data = 0.0075, hover = ""},
						{description = "1%", data = 0.01, hover = ""},
						{description = "2%", data = 0.02, hover = ""},
						{description = "3%", data = 0.03, hover = ""},
						{description = "4%", data = 0.04, hover = ""},
						{description = "5%", data = 0.05, hover = ""},
						{description = "6%", data = 0.01, hover = ""},
						{description = "7%", data = 0.01, hover = ""},
						{description = "8%", data = 0.01, hover = ""},
						{description = "9%", data = 0.01, hover = ""},
						{description = "10%", data = 0.1, hover = ""},
						{description = "20%", data = 0.2, hover = ""},
						{description = "30%", data = 0.3, hover = ""},
						{description = "40%", data = 0.4, hover = ""},
						{description = "50%", data = 0.5, hover = ""},
					},
		default = 0.1,
	},
	{
		name = "marble",
		label = "Marble",
		hover = "the probability of dropping marble.",
		options =	{
						{description = "0", data = 0, hover = ""},
						{description = "0.25%", data = 0.0025, hover = ""},
						{description = "0.5%", data = 0.005, hover = ""},
						{description = "0.75%", data = 0.0075, hover = ""},
						{description = "1%", data = 0.01, hover = ""},
						{description = "2%", data = 0.02, hover = ""},
						{description = "3%", data = 0.03, hover = ""},
						{description = "4%", data = 0.04, hover = ""},
						{description = "5%", data = 0.05, hover = ""},
						{description = "6%", data = 0.01, hover = ""},
						{description = "7%", data = 0.01, hover = ""},
						{description = "8%", data = 0.01, hover = ""},
						{description = "9%", data = 0.01, hover = ""},
						{description = "10%", data = 0.1, hover = ""},
						{description = "20%", data = 0.2, hover = ""},
						{description = "30%", data = 0.3, hover = ""},
						{description = "40%", data = 0.4, hover = ""},
						{description = "50%", data = 0.5, hover = ""},
					},
		default = 0.1,
	},
	{
		name = "moonrocknugget",
		label = "Moon Rock",
		hover = "the probability of Moon Rock.",
		options =	{
						{description = "0", data = 0, hover = ""},
						{description = "0.25%", data = 0.0025, hover = ""},
						{description = "0.5%", data = 0.005, hover = ""},
						{description = "0.75%", data = 0.0075, hover = ""},
						{description = "1%", data = 0.01, hover = ""},
						{description = "2%", data = 0.02, hover = ""},
						{description = "3%", data = 0.03, hover = ""},
						{description = "4%", data = 0.04, hover = ""},
						{description = "5%", data = 0.05, hover = ""},
						{description = "6%", data = 0.01, hover = ""},
						{description = "7%", data = 0.01, hover = ""},
						{description = "8%", data = 0.01, hover = ""},
						{description = "9%", data = 0.01, hover = ""},
						{description = "10%", data = 0.1, hover = ""},
						{description = "20%", data = 0.2, hover = ""},
						{description = "30%", data = 0.3, hover = ""},
						{description = "40%", data = 0.4, hover = ""},
						{description = "50%", data = 0.5, hover = ""},
					},
		default = 0.1,
	},
	{
		name = "redgem",
		label = "Red gem",
		hover = "the probability of dropping red gem.",
		options =	{
						{description = "0", data = 0, hover = ""},
						{description = "0.25%", data = 0.0025, hover = ""},
						{description = "0.5%", data = 0.005, hover = ""},
						{description = "0.75%", data = 0.0075, hover = ""},
						{description = "1%", data = 0.01, hover = ""},
						{description = "2%", data = 0.02, hover = ""},
						{description = "3%", data = 0.03, hover = ""},
						{description = "4%", data = 0.04, hover = ""},
						{description = "5%", data = 0.05, hover = ""},
						{description = "6%", data = 0.01, hover = ""},
						{description = "7%", data = 0.01, hover = ""},
						{description = "8%", data = 0.01, hover = ""},
						{description = "9%", data = 0.01, hover = ""},
						{description = "10%", data = 0.1, hover = ""},
						{description = "20%", data = 0.2, hover = ""},
						{description = "30%", data = 0.3, hover = ""},
					},
		default = 0.02,
	},
	{
		name = "bluegem",
		label = "Blue gem",
		hover = "the probability of dropping blue gem.",
		options =	{
						{description = "0", data = 0, hover = ""},
						{description = "0.25%", data = 0.0025, hover = ""},
						{description = "0.5%", data = 0.005, hover = ""},
						{description = "0.75%", data = 0.0075, hover = ""},
						{description = "1%", data = 0.01, hover = ""},
						{description = "2%", data = 0.02, hover = ""},
						{description = "3%", data = 0.03, hover = ""},
						{description = "4%", data = 0.04, hover = ""},
						{description = "5%", data = 0.05, hover = ""},
						{description = "6%", data = 0.01, hover = ""},
						{description = "7%", data = 0.01, hover = ""},
						{description = "8%", data = 0.01, hover = ""},
						{description = "9%", data = 0.01, hover = ""},
						{description = "10%", data = 0.1, hover = ""},
						{description = "20%", data = 0.2, hover = ""},
						{description = "30%", data = 0.3, hover = ""},
					},
		default = 0.02,
	},
	{
		name = "purplegem",
		label = "Purple gem",
		hover = "the probability of dropping purple gem.",
		options =	{
						{description = "0", data = 0, hover = ""},
						{description = "0.25%", data = 0.0025, hover = ""},
						{description = "0.5%", data = 0.005, hover = ""},
						{description = "0.75%", data = 0.0075, hover = ""},
						{description = "1%", data = 0.01, hover = ""},
						{description = "2%", data = 0.02, hover = ""},
						{description = "3%", data = 0.03, hover = ""},
						{description = "4%", data = 0.04, hover = ""},
						{description = "5%", data = 0.05, hover = ""},
						{description = "6%", data = 0.01, hover = ""},
						{description = "7%", data = 0.01, hover = ""},
						{description = "8%", data = 0.01, hover = ""},
						{description = "9%", data = 0.01, hover = ""},
						{description = "10%", data = 0.1, hover = ""},
					},
		default = 0.01,
	},
	{
		name = "orangegem",
		label = "Orange gem",
		hover = "the probability of dropping orange gem.",
		options =	{
						{description = "0", data = 0, hover = ""},
						{description = "0.25%", data = 0.0025, hover = ""},
						{description = "0.5%", data = 0.005, hover = ""},
						{description = "0.75%", data = 0.0075, hover = ""},
						{description = "1%", data = 0.01, hover = ""},
						{description = "2%", data = 0.02, hover = ""},
						{description = "3%", data = 0.03, hover = ""},
						{description = "4%", data = 0.04, hover = ""},
						{description = "5%", data = 0.05, hover = ""},
						{description = "6%", data = 0.01, hover = ""},
						{description = "7%", data = 0.01, hover = ""},
						{description = "8%", data = 0.01, hover = ""},
						{description = "9%", data = 0.01, hover = ""},
						{description = "10%", data = 0.1, hover = ""},
						{description = "20%", data = 0.2, hover = ""},
						{description = "30%", data = 0.3, hover = ""},
					},
		default = 0.02,
	},
	{
		name = "yellowgem",
		label = "Yellow gem",
		hover = "the probability of dropping yellow gem.",
		options =	{
						{description = "0", data = 0, hover = ""},
						{description = "0.25%", data = 0.0025, hover = ""},
						{description = "0.5%", data = 0.005, hover = ""},
						{description = "0.75%", data = 0.0075, hover = ""},
						{description = "1%", data = 0.01, hover = ""},
						{description = "2%", data = 0.02, hover = ""},
						{description = "3%", data = 0.03, hover = ""},
						{description = "4%", data = 0.04, hover = ""},
						{description = "5%", data = 0.05, hover = ""},
						{description = "6%", data = 0.01, hover = ""},
						{description = "7%", data = 0.01, hover = ""},
						{description = "8%", data = 0.01, hover = ""},
						{description = "9%", data = 0.01, hover = ""},
						{description = "10%", data = 0.1, hover = ""},
						{description = "20%", data = 0.2, hover = ""},
						{description = "30%", data = 0.3, hover = ""},
					},
		default = 0.02,
	},
	{
		name = "greengem",
		label = "Green gem",
		hover = "the probability of dropping green gem.",
		options =	{
						{description = "0", data = 0, hover = ""},
						{description = "0.25%", data = 0.0025, hover = ""},
						{description = "0.5%", data = 0.005, hover = ""},
						{description = "0.75%", data = 0.0075, hover = ""},
						{description = "1%", data = 0.01, hover = ""},
						{description = "2%", data = 0.02, hover = ""},
						{description = "3%", data = 0.03, hover = ""},
						{description = "4%", data = 0.04, hover = ""},
						{description = "5%", data = 0.05, hover = ""},
						{description = "6%", data = 0.01, hover = ""},
						{description = "7%", data = 0.01, hover = ""},
						{description = "8%", data = 0.01, hover = ""},
						{description = "9%", data = 0.01, hover = ""},
						{description = "10%", data = 0.1, hover = ""},
						{description = "20%", data = 0.2, hover = ""},
						{description = "30%", data = 0.3, hover = ""},
					},
		default = 0.02,
	},
}